ToDo List project
cgcarlosg/ToDoList pull request #2
Opened 2021-03-05 23:25 UTC by cgcarlosg

At this pull request I made a Todo project with all functionalities below:

Create todo with title, description, priority, complete check and, due date
Create projects to group Todos
Change icon-color depending on Todo priority
Remove when Todo is marked as complete
Delete todo
Use WebPack to create a bundle js file
Create WebPack configuration to bundle js file
Add scripts to package.json in order to run webpacks' build and watch

2021-03-06 06:27 UTC, Forison requested changes
## Status::Changes Required

# 👋 Team

## You have done a good job on this one so far, however, here are a few issues we have to address to get this approved💪.

* [ ] Do not commit unrelated files. Files like `DS_STORE` , `.VSCODE` should be remove.
* [ ] The link of the live link does not direct to the right path.
* [ ] User can delete a to-do.
* [ ] There is a 'default' project.
* [ ] Let us add the necessary run common commands like `build`, `development` should be in `package.json` inside \`scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622602/))
should look like this,
```
javascript
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  },
```
to make development more flexible.
* [ ] Let use arrow functions instead of the `function` keyword, check my comments below.

#### That is it, kindly make the change and submit a re-review😎.

#### Happy coding😇
Addo Forison

2021-03-06 06:27 UTC, Forison commented on src/index.js
> +function colorTasks(selectedList) {
* [ ] Let us use arrow function

2021-03-06 06:27 UTC, Forison commented on src/index.js
> +function openOrCloseUpdateTaskForm() {
* [ ] Let us use arrow function

2021-03-06 06:27 UTC, Forison commented on src/index.js
> +function renderTasks(selectedList) {
* [ ] Let us use arrow function

2021-03-06 06:27 UTC, Forison commented on src/index.js
> +function render() {
* [ ] Let us use arrow function

2021-03-06 06:27 UTC, Forison commented on src/index.js
> +function createList() {
* [ ] Let us use arrow function

2021-03-06 06:27 UTC, Forison commented on src/index.js
> +function createTask() {
* [ ] Let us use arrow function and other areas when function keyword was used to define a function

2021-03-08 22:07 UTC, cgcarlosg commented
Hi. thanks for the feedback.

We have one question:

The button "Clear completed tasks" is the one used to remove or delete selected tasks.  Then we did not understand the comment about delete tasks.

Any additional comments please let us know.  Thanks

2021-03-09 00:14 UTC, NtwaliHeritier reviewed
### **STATUS: CHANGES REQUESTED🛑🛑**

Hello team,
The design is very attractive. Great work on making the requested changes. 
However one small change is required.

[REQUIRED]: Add the possibility to delete a task even when it is not completed.
[REQUIRED]: In your readme file, I think the correct way to run the project is to run npm run start instead of double clicking the index.html. Kindly modify it in the readme file.

That's it👍👍👍
Make the requested changes and ask for another review👌

2021-03-10 02:10 UTC, arslanbisharat approved these changes
# Approved :clap:

Hello Developer, wave:

Thank You for submitting this Pull Request. I am thrilled to announce that your project has met all the minimum requirements and now it is approved. :clap:

I am wishing you very good luck with the next project. :smile:

Once again, Congratulations!:joy:

**Best,
Arslan Bisharat(PT-TSE)
Slack: @arslanbisharat**

2021-03-10 04:38 UTC, merged